name: Generate lists

on:
  schedule: # https://crontab.guru
    - cron: '0 */4 * * *' # At minute 0 past every 4nd hour.

  workflow_dispatch:

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          # lfs: true

      # - name: Set up Git LFS
      #   run: git lfs install

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download lists
        run: node scripts/generate/file-processor/download.js --expose-gc

      - name: Generate lists
        run: node scripts/generate/file-processor/generate.js

      - name: Generate header
        run: node scripts/generate/file-processor/header.js

      - name: Prepare templates
        run: node scripts/prepare-templates.js

      - name: Remove duplicates
        run: node scripts/prepare-lines.js

      - name: Add files to staging
        run: git add .

      - name: Commit and push changes
        run: |
          git config --global user.name "Sefinek Actions"
          git config --global user.email "sefinek.actions@gmail.com"
          if [ -n "$(git status -s)" ]; then
            git status
            MODIFIED_FILES=$(git diff --name-only HEAD)
            git commit -m "Update lists [$(echo "$MODIFIED_FILES" | wc -l)] - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" -m "$MODIFIED_FILES"
            git push origin main
          else
            echo "Canceled. No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.SEFINEK_ACTIONS_PAT }}
