name: Generate lists

on:
  schedule: # https://crontab.guru
    - cron: '0 */4 * * *' # At minute 0 past every 4nd hour.

  workflow_dispatch:

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download lists
        run: node scripts/generate/file-processor/download.js --expose-gc

      - name: Generate lists
        run: node scripts/generate/file-processor/generate.js

      - name: Generate header
        run: node scripts/generate/file-processor/header.js

      - name: Prepare templates
        run: node scripts/prepare-templates.js

      - name: Remove duplicates
        run: node scripts/prepare-lines.js

      - name: Remove domains that are on the whitelist
        run: node scripts/whitelist.js

      - name: Set valid encoding
        run: node scripts/set-valid-encoding.js

      - name: Count domains
        run: node scripts/update-number-of-domains.js --ignore-question

      - name: Run git pull
        run: git pull

      - name: Add files to staging
        run: git add .

      - name: Commit and push changes
        run: |
          git config user.name "Sefinek Actions"
          git config user.email "sefinek.actions@gmail.com"
          if [ -n "$(git status -s)" ]; then
            FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
            MODIFIED_FILES=$(git diff --name-only HEAD)
            git commit -am "Update lists [$FILE_COUNT files]" -m "$MODIFIED_FILES"
            git push origin main
          else
            echo "Canceled. No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.SEFINEK_ACTIONS_PAT }}